### ISSUE TITLE
Im tired of this issue typing just add me on skype

### ISSUE THREAD

**Issue by TomThatHatesModCrash** [TeamBR-Modding/ModernAlchemy#37]
Just add me on skype i will show you everything what problems i got

**Comment by TomThatHatesModCrash** [comment]
Skype: toms.toms61

**Comment by Dyonovan** [comment]
Sorry but I wont. Please stop opening new issues.

**Comment by TomThatHatesModCrash** [comment]
ok :(

**Comment by TomThatHatesModCrash** [comment]
then i will try figuring out this thing T_T
